### ISSUE TITLE
Join forces PMD

### ISSUE THREAD

**Issue by rsoesemann** [Force-Config-Control/lightning-flow-scanner-core#17]
Just stumbled over your great tool and wondered if it wouldn't make sense to port your rules (or even merge it partially) with PMD. Just recently @aidan-harding  contributed code to make Flow rules possible.

- https://github.com/pmd/pmd/issues/3413 [xml] New language to detect issues in Salesforce Flow
- https://github.com/pmd/pmd/pull/3417

What do you think? If contributing your Flow knowledge to #PMD sounds not crazy for you, ping me and I tell you how to do it.

**Comment by aidan-harding** [comment]
Hi @RubenHalman 

Sorry for being fairly unresponsive on this. I've was all-in working on the PMD Flow language for a bit, but I've had other projects take away my time over the past month or so.

It would be great to get input on the rules when I've got my implementation ready to write some rules.

The current state in PMD is that 2 things were required to check Flow:

1. Some language detection changes so that PMD could support different languages with the same file extension. For this, I've made a small change to PMD. My change forces PMD to use the language you provide as a command-line argument instead of trying to match for itself. This was released in PMD and gives us enough for an MVP of Flow checking in PMD. The ideal would be something smarter so that you can point PMD at a directory tree with multiple languages and it could auto-detect across multiple languages. That was too big for me to take on initially, but it's tracked here https://github.com/pmd/pmd/issues/461
1. A new PMD language module for Flow. Although Flow is stored in XML, the XML structure of the files doesn't represent the structure of the Flow directly. I imagine that your tool does the same thing of reading in the XML and building the Flow graph in memory so that you can do analysis on it. Since PMD already has support for easily writing rules against an AST for other languages, my intention is to translate the Flow into an AST. Then we can make use of the existing PMD tool for writing rules. 

Once I get back and finish writing the Flow language module, I'll definitely look through your rules as an initial set of rules of PMD.

**Comment by RubenHalman** [comment]
@aidan-harding No worries.

These are the same rules as from the standard help [documentation](https://help.salesforce.com/articleView?id=sf.flow_prep_bestpractices.htm&type=5).

I think I could help you help with the implementation of the language module?

**Comment by RubenHalman** [comment]
@rsoesemann it does not make sense to me to keep this ticket open in the lightning flow scanner project, since it is not aimed at changing the code of this repository. Thank you for reaching out and let me know if and how I can help, but also, please do star / share the project to spark an initial discussion in the community if you'd like!
